### ISSUE TITLE
Take one file as input rather than complete directory

### ISSUE THREAD

**Issue by jimmybgammyknee** [ningbioinfostruggling/FeatureCount2GCT#4]
Most people will have one table with all genes (rows) and samples (columns) in it, so are you able to add the option to take one file rather than a complete directory of separated samples?

**Comment by jimmybgammyknee** [comment]
This hasnt been implemented, so youll need to reopen this issue

**Comment by jimmybgammyknee** [comment]
This hasnt been implemented, so youll need to reopen this issue. 

Heres an example:
[example.txt](https://github.com/ningbioinfostruggling/FeatureCount2GCT/files/1878495/example.txt)

**Comment by ningbioinfo** [comment]
Should be working now.
